/*
 Do not edit this file. 
 For local testing use server-debug.js
*/
let startServers = require('./server-util').startServers;
let numCPUs = require('os').cpus().length;
 
startServers(2 * numCPUs);
